"""add calculations table

Revision ID: ff5724fe247d
Revises: 
Create Date: 2025-07-28 04:16:25.297093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5724fe247d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Numeric(scale=4), nullable=False),
    sa.Column('b', sa.Numeric(scale=4), nullable=False),
    sa.Column('type', sa.Enum('add', 'sub', 'multiply', 'divide', name='calctype'), nullable=False),
    sa.Column('result', sa.Numeric(scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.drop_table('calculations')
    # ### end Alembic commands ###
